### ISSUE TITLE
大佬，这种banner效果咋实现啊

### ISSUE THREAD

**Issue by lujun525** [youlookwhat/SBannerView#1]
![Screenshot_20221014_154539](https://user-images.githubusercontent.com/13325765/195791767-fc33fe8f-2d11-4382-8412-f0548c2c92de.jpg)

**Comment by youlookwhat** [comment]
我觉得这是要用 RecyclerView 自定义 LinearLayoutManager 来做哦，例如 https://cloud.tencent.com/developer/article/1608059

可以拿过来改改之类的

**Comment by lujun525** [comment]
我这个还要实现下面viewpager切换，上面图片画廊跟着切换，有联动效果，好难哦

**Comment by youlookwhat** [comment]
下面的viewpager切换会有监听，上面的画廊应该只用设置到第一个就可以了。

**Comment by youlookwhat** [comment]
是有点复杂哦
